CREATE TABLE IF NOT EXISTS roles (
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);


INSERT INTO roles (id, name)
VALUES (1, 'ADMIN')
ON CONFLICT DO NOTHING;

INSERT INTO roles (id, name)
VALUES (2, 'SELLER')
ON CONFLICT DO NOTHING;

INSERT INTO roles (id, name)
VALUES (3, 'CUSTOMER')
ON CONFLICT DO NOTHING;
